BEGIN;
INSERT INTO \"Estado\" (\"id_estado\", \"nombre_estado\") VALUES (9, 'TEMP_ATENDIDO');
UPDATE \"Atencion\" SET \"id_estado_actual\" = 9 WHERE \"id_estado_actual\" = 6;
UPDATE \"Historial_Atencion\" SET \"id_estado\" = 9 WHERE \"id_estado\" = 6;
UPDATE \"Atencion\" SET \"id_estado_actual\" = 6 WHERE \"id_estado_actual\" = 7;
UPDATE \"Historial_Atencion\" SET \"id_estado\" = 6 WHERE \"id_estado\" = 7;
UPDATE \"Atencion\" SET \"id_estado_actual\" = 7 WHERE \"id_estado_actual\" = 8;
UPDATE \"Historial_Atencion\" SET \"id_estado\" = 7 WHERE \"id_estado\" = 8;
UPDATE \"Atencion\" SET \"id_estado_actual\" = 8 WHERE \"id_estado_actual\" = 9;
UPDATE \"Historial_Atencion\" SET \"id_estado\" = 8 WHERE \"id_estado\" = 9;
UPDATE \"Estado\" SET \"nombre_estado\" = 'Ausente' WHERE \"id_estado\" = 6;
UPDATE \"Estado\" SET \"nombre_estado\" = 'Espera de clave' WHERE \"id_estado\" = 7;
UPDATE \"Estado\" SET \"nombre_estado\" = 'Atendido' WHERE \"id_estado\" = 8;
DELETE FROM \"Estado\" WHERE \"id_estado\" = 9;
SELECT pg_catalog.setval('public.\"Estado_id_estado_seq\"', 8, true);
COMMIT;
