const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const http = require('http');
const { Server } = require('socket.io');
const dotenv = require('dotenv');
const path = require('path');
const pool = require('./src/config/db');
const logger = require('./src/config/logger');

dotenv.config({ path: path.join(__dirname, '.env') });

const app = express();
const server = http.createServer(app);

app.use(helmet());

const corsOrigins = process.env.CORS_ORIGIN
  ? process.env.CORS_ORIGIN.split(',').map(s => s.trim())
  : ['http://localhost:4200', 'http://localhost:4201', 'http://localhost'];

const io = new Server(server, {
  cors: {
    origin: corsOrigins,
    methods: ['GET', 'POST', 'PUT', 'DELETE'],
  },
});

app.use(cors({
  origin: corsOrigins,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
  credentials: true,
}));
app.use(express.json());

app.use((req, res, next) => {
  req.io = io;
  next();
});

pool.query('SELECT NOW()', async (err) => {
  if (err) {
    logger.error('Error al conectar con la base de datos', { error: err.message });
  } else {
    logger.info('Conexión a PostgreSQL exitosa');
    try {
      await pool.query(
        'ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_consultorio INTEGER REFERENCES "Consultorios"("id_consultorio")',
      );
      logger.info('Columna id_consultorio asegurada en tabla Atencion');

      await pool.query(
        'ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_cliente INTEGER REFERENCES "cliente"("id_cliente")',
      );
      logger.info('Columna id_cliente asegurada en tabla Atencion');

      await pool.query('DROP TABLE IF EXISTS "turnos" CASCADE');
      logger.info('Tabla legacy turnos eliminada');

      await pool.query(`
        CREATE TABLE IF NOT EXISTS "tipo_cliente" (
          "id_tipo_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "nombre" varchar NOT NULL
        );
        CREATE TABLE IF NOT EXISTS "cliente" (
          "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "id_tipo_cliente" integer NOT NULL REFERENCES "tipo_cliente"("id_tipo_cliente"),
          "nombre" varchar NOT NULL,
          "id_sede" integer REFERENCES "Sedes"("id_sede")
        );
        INSERT INTO "tipo_cliente" ("id_tipo_cliente", "nombre") VALUES
          (1, 'Particular'),
          (2, 'Aseguradora')
        ON CONFLICT ("id_tipo_cliente") DO UPDATE SET
          "nombre" = EXCLUDED."nombre";
      `);
      logger.info('Tablas tipo_cliente y cliente aseguradas');
    } catch (alterError) {
      logger.error('Error al asegurar tablas nuevas', { error: alterError.message });
    }
  }
});

app.get('/api/health', (req, res) => {
  res.status(200).json({ status: 'ok', message: 'API funcionando correctamente' });
});

const authRoutes = require('./src/routes/auth.routes');
const adminRoutes = require('./src/routes/admin.routes');
const turnosRoutes = require('./src/routes/turnos.routes');
const consultoriosRoutes = require('./src/routes/consultorios.routes');
const recepcionRoutes = require('./src/routes/recepcion.routes');
const sharedRoutes = require('./src/routes/shared.routes');
const medicoRoutes = require('./src/routes/medico.routes');
const especialidadesRoutes = require('./src/routes/especialidades.routes');

app.use('/api/auth', authRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/shared', sharedRoutes);
app.use('/api/turnos', turnosRoutes);
app.use('/api/consultorios', consultoriosRoutes);
app.use('/api/recepcion', recepcionRoutes);
app.use('/api/medico', medicoRoutes);
app.use('/api/especialidades', especialidadesRoutes);

app.use((err, req, res, next) => {
  logger.error('Error no controlado', { error: err.message, stack: err.stack });
  res.status(500).json({ mensaje: 'Error interno del servidor' });
});

io.on('connection', (socket) => {
  logger.info(`Cliente conectado: ${socket.id}`);
  socket.on('disconnect', () => {
    logger.info(`Cliente desconectado: ${socket.id}`);
  });
});

const PORT = process.env.PORT || 3001;
if (require.main === module) {
  server.listen(PORT, () => {
    logger.info(`Servidor backend corriendo en http://localhost:${PORT}`);
  });
  server.on('error', (err) => {
    if (err.code === 'EADDRINUSE') {
      logger.warn(`Puerto ${PORT} en uso, liberando...`);
      const { execSync } = require('child_process');
      try {
        const output = execSync(
          `netstat -ano | findstr :${PORT} | findstr LISTENING`,
          { shell: true, encoding: 'utf8', timeout: 3000 },
        );
        output.trim().split(/\r?\n/).forEach(line => {
          const parts = line.trim().split(/\s+/);
          const pid = parseInt(parts[parts.length - 1]);
          if (!isNaN(pid)) {
            try { process.kill(pid, 'SIGTERM'); } catch (e) { /* ignore */ }
          }
        });
      } catch (e) { /* netstat no match or timeout */ }
      server.close(() => {
        server.listen(PORT);
      });
    } else {
      logger.error('Error al iniciar servidor', { error: err.message });
    }
  });
}

module.exports = { app, server, io };
