const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const http = require('http');
const { Server } = require('socket.io');
const dotenv = require('dotenv');
const path = require('path');
const jwt = require('jsonwebtoken');
const pool = require('./src/config/db');
const logger = require('./src/config/logger');
const requestId = require('./src/middleware/requestId');

dotenv.config({ path: path.join(__dirname, '.env') });

const app = express();
app.set('trust proxy', true);
const server = http.createServer(app);

app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'"],
      styleSrc: ["'self'", "'unsafe-inline'"],
      imgSrc: ["'self'", "data:", "https://ui-avatars.com"],
      fontSrc: ["'self'"],
      connectSrc: ["'self'", "ws:", "http://localhost:*"],
      frameAncestors: ["'none'"],
      baseUri: ["'self'"],
    },
  },
  hsts: {
    maxAge: 63072000,
    includeSubDomains: true,
    preload: true,
  },
  referrerPolicy: { policy: 'strict-origin-when-cross-origin' },
}));

const corsOrigins = process.env.CORS_ORIGIN
  ? process.env.CORS_ORIGIN.split(',').map(s => s.trim())
  : ['http://localhost:4200', 'http://localhost:4201', 'http://localhost'];

const io = new Server(server, {
  cors: {
    origin: corsOrigins,
    methods: ['GET', 'POST', 'PUT', 'DELETE'],
  },
  pingTimeout: 60000,
  pingInterval: 25000,
});

app.use(cors({
  origin: corsOrigins,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
  credentials: true,
}));
app.use(express.json({ limit: '100kb' }));

app.use((req, res, next) => {
  req.io = io;
  next();
});
app.use(requestId);

const PORT = process.env.PORT || 3001;

const startServer = async () => {
  try {
    await pool.query('SELECT NOW()');
    logger.info('Conexión a PostgreSQL exitosa');

    // MIGRACIONES
    try {
      await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_consultorio INTEGER REFERENCES "Consultorios"("id_consultorio")');
      await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_cliente INTEGER REFERENCES "cliente"("id_cliente")');
      await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_medico INTEGER REFERENCES "Usuarios"("id_usuario")');
      await pool.query('DROP TABLE IF EXISTS "turnos" CASCADE');

      await pool.query(`
        CREATE TABLE IF NOT EXISTS "tipo_cliente" (
          "id_tipo_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "nombre" varchar NOT NULL
        );
        CREATE TABLE IF NOT EXISTS "cliente" (
          "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "id_tipo_cliente" integer NOT NULL REFERENCES "tipo_cliente"("id_tipo_cliente"),
          "nombre" varchar NOT NULL,
          "id_sede" integer REFERENCES "Sedes"("id_sede")
        );
        INSERT INTO "tipo_cliente" ("id_tipo_cliente", "nombre") VALUES (1, 'Particular'), (2, 'Aseguradora')
        ON CONFLICT ("id_tipo_cliente") DO UPDATE SET "nombre" = EXCLUDED."nombre";
      `);

      await pool.query(`
        CREATE TABLE IF NOT EXISTS "Recuperacion_Clave" (
          "id_recuperacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "id_usuario" INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario"),
          "codigo" VARCHAR(6) NOT NULL,
          "expiracion" TIMESTAMP NOT NULL,
          "usado" BOOLEAN DEFAULT false,
          "fecha_creacion" TIMESTAMP DEFAULT (now())
        );
      `);

      await pool.query(`
        CREATE TABLE IF NOT EXISTS "Roles" (
          "id_rol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "nombre" VARCHAR NOT NULL,
          "key" VARCHAR NOT NULL UNIQUE,
          "id_sede" INTEGER REFERENCES "Sedes"("id_sede"),
          "activo" BOOLEAN DEFAULT true,
          "fecha_creacion" TIMESTAMP DEFAULT (now())
        );
        INSERT INTO "Roles" ("nombre", "key", "id_sede", "activo") VALUES
          ('ADMINISTRADOR', 'administrador', NULL, true),
          ('RECEPCIONISTA', 'recepcionista', NULL, true),
          ('MEDICO', 'medico', NULL, true),
          ('COORDINADOR', 'coordinador', NULL, true),
          ('ANALISTA', 'analista', NULL, true),
          ('LABORATORIO', 'laboratorio', NULL, true),
          ('IMAGENES', 'imagenes', NULL, true)
        ON CONFLICT ("key") DO NOTHING;
      `);

      try {
        await pool.query(`
          UPDATE "Roles" SET nombre = UPPER(TRANSLATE(nombre, 'áéíóúÁÉÍÓÚ', 'aeiouAEIOU'));
          UPDATE "Roles" SET nombre = REPLACE(nombre, ' ', '');
        `);
      } catch (errNorm) {
        logger.warn('Aviso: No se pudieron normalizar nombres de roles', { error: errNorm.message });
      }

      await pool.query('ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS sesion_token VARCHAR DEFAULT NULL');
      await pool.query('ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS id_rol INTEGER REFERENCES "Roles"("id_rol")');
      const checkRolCol = await pool.query("SELECT column_name FROM information_schema.columns WHERE LOWER(table_name) = 'usuarios' AND LOWER(column_name) = 'rol'");

      if (checkRolCol.rowCount > 0) {
        logger.info('Migrando datos de "rol" a "id_rol"...');
        await pool.query('UPDATE "Usuarios" u SET id_rol = r.id_rol FROM "Roles" r WHERE u.rol = r.key AND u.id_rol IS NULL');
        await pool.query('ALTER TABLE "Usuarios" DROP CONSTRAINT IF EXISTS fk_usuarios_rol');
        await pool.query('ALTER TABLE "Usuarios" DROP COLUMN IF EXISTS rol');
      }

      // Migración: eliminar rol APS, reordenar IDs
      try {
        const apsRole = await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'aps'`);
        if (apsRole.rowCount > 0) {
          const apsId = apsRole.rows[0].id_rol;
          const analistaId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'analista'`)).rows[0].id_rol;
          const coordId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'coordinador'`)).rows[0].id_rol;
          const labId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'laboratorio'`)).rows[0].id_rol;
          const imgId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'imagenes'`)).rows[0].id_rol;

          const client = await pool.connect();
          try {
            await client.query('BEGIN');
            await client.query('UPDATE "Usuarios" SET id_rol = $1 WHERE id_rol = $2', [analistaId, apsId]);
            await client.query('DELETE FROM "Roles" WHERE key = $1', ['aps']);
            await client.query('UPDATE "Usuarios" SET id_rol = 4 WHERE id_rol = $1', [coordId]);
            await client.query('UPDATE "Roles" SET id_rol = 4 WHERE key = $1', ['coordinador']);
            await client.query('UPDATE "Usuarios" SET id_rol = 5 WHERE id_rol = $1', [analistaId]);
            await client.query('UPDATE "Roles" SET id_rol = 5 WHERE key = $1', ['analista']);
            await client.query('UPDATE "Usuarios" SET id_rol = 6 WHERE id_rol = $1', [labId]);
            await client.query('UPDATE "Roles" SET id_rol = 6 WHERE key = $1', ['laboratorio']);
            await client.query('UPDATE "Usuarios" SET id_rol = 7 WHERE id_rol = $1', [imgId]);
            await client.query('UPDATE "Roles" SET id_rol = 7 WHERE key = $1', ['imagenes']);
            await client.query('COMMIT');
            logger.info('Rol APS eliminado, usuarios migrados a Analista, IDs reordenados');
          } catch (txErr) {
            await client.query('ROLLBACK');
            logger.error('Error migrando rol APS', { error: txErr.message });
          } finally {
            client.release();
          }
        }
      } catch (apsErr) {
        logger.warn('Error consultando rol APS (probablemente ya migrado)', { error: apsErr.message });
      }

      logger.info('Base de datos inicializada correctamente');
    } catch (dbErr) {
      logger.error('Error crítico inicializando la base de datos', { error: dbErr.message });
    }

    server.listen(PORT, () => {
      logger.info(`Servidor backend corriendo en http://localhost:${PORT}`);
    });

  } catch (err) {
    logger.error('Error al conectar con la base de datos', { error: err.message });
    process.exit(1);
  }
};

if (require.main === module) {
  startServer();
}

app.get('/api/health', (req, res) => {
  res.status(200).json({ status: 'ok', message: 'API funcionando correctamente' });
});

const authRoutes = require('./src/routes/auth.routes');
const adminRoutes = require('./src/routes/admin.routes');
const turnosRoutes = require('./src/routes/turnos.routes');
const consultoriosRoutes = require('./src/routes/consultorios.routes');
const recepcionRoutes = require('./src/routes/recepcion.routes');
const sharedRoutes = require('./src/routes/shared.routes');
const medicoRoutes = require('./src/routes/medico.routes');
const especialidadesRoutes = require('./src/routes/especialidades.routes');
const turneroRoutes = require('./src/routes/turnero.routes');
const recuperacionRoutes = require('./src/routes/recuperacion.routes');

app.use('/api/auth', authRoutes);
app.use('/api/auth/recuperacion', recuperacionRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/shared', sharedRoutes);
app.use('/api/turnos', turnosRoutes);
app.use('/api/consultorios', consultoriosRoutes);
app.use('/api/recepcion', recepcionRoutes);
app.use('/api/medico', medicoRoutes);
app.use('/api/especialidades', especialidadesRoutes);
app.use('/api/turnero', turneroRoutes);

app.use((err, req, res, next) => {
  logger.error('Error no controlado', { error: err.message, stack: err.stack });
  res.status(500).json({ mensaje: 'Error interno del servidor' });
});

io.use((socket, next) => {
  const token = socket.handshake.auth?.token || socket.handshake.query?.token;
  if (!token) {
    socket.usuario = null;
    return next();
  }
  jwt.verify(token, process.env.JWT_SECRET, (err, decoded) => {
    if (err) {
      socket.usuario = null;
      return next();
    }
    socket.usuario = decoded;
    next();
  });
});

io.on('connection', (socket) => {
  logger.info(`Cliente conectado: ${socket.id}${socket.usuario ? ` (${socket.usuario.rol})` : ' (anónimo)'}`);
  socket.on('disconnect', () => {
    logger.info(`Cliente desconectado: ${socket.id}`);
  });
});

process.on('SIGTERM', () => {
  logger.info('SIGTERM recibido, cerrando servidor...');
  server.close(() => {
    pool.end(() => process.exit(0));
  });
});

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    logger.warn(`Puerto ${PORT} en uso, liberando...`);
    const { execSync } = require('child_process');
    try {
      const output = execSync(
        `netstat -ano | findstr :${PORT} | findstr LISTENING`,
        { shell: true, encoding: 'utf8', timeout: 3000 },
      );
      output.trim().split(/\r?\n/).forEach(line => {
        const parts = line.trim().split(/\s+/);
        const pid = parseInt(parts[parts.length - 1]);
        if (!isNaN(pid)) {
          try { process.kill(pid, 'SIGTERM'); } catch (e) { /* ignore */ }
        }
      });
    } catch (e) { /* netstat no match or timeout */ }
    server.close(() => {
      server.listen(PORT);
    });
  } else {
    logger.error('Error al iniciar servidor', { error: err.message });
  }
});

module.exports = { app, server, io };
