const pool = require('./src/config/db');
const logger = require('./src/config/logger');

/**
 * Ejecuta las migraciones automáticas de la base de datos al iniciar
 * el servidor. Crea tablas faltantes, agrega columnas, normaliza datos
 * existentes y garantiza que el esquema esté actualizado sin intervención
 * manual.
 */
const runMigrations = async () => {
  logger.info('Ejecutando migraciones...');

  await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_consultorio INTEGER REFERENCES "Consultorios"("id_consultorio")');
  await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_cliente INTEGER REFERENCES "cliente"("id_cliente") ON DELETE SET NULL');
  await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_medico INTEGER REFERENCES "Usuarios"("id_usuario")');

  // Permitir eliminar aseguradoras: al borrar una, las atenciones asociadas
  // se conservan pero quedan sin aseguradora (id_cliente = NULL).
  const fkCliente = await pool.query(`
    SELECT conname FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON t.relnamespace = n.oid
    JOIN pg_class r ON c.confrelid = r.oid
    WHERE t.relname = 'Atencion'
      AND n.nspname = 'public'
      AND r.relname = 'cliente'
      AND c.contype = 'f'
  `);
  for (const row of fkCliente.rows) {
    await pool.query(`ALTER TABLE "Atencion" DROP CONSTRAINT IF EXISTS "${row.conname}"`);
  }
  await pool.query(`
    ALTER TABLE "Atencion"
    ADD CONSTRAINT "Atencion_id_cliente_fkey"
    FOREIGN KEY ("id_cliente") REFERENCES "cliente"("id_cliente") ON DELETE SET NULL
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "tipo_cliente" (
      "id_tipo_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "nombre" varchar NOT NULL
    );
    CREATE TABLE IF NOT EXISTS "cliente" (
      "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_tipo_cliente" integer NOT NULL REFERENCES "tipo_cliente"("id_tipo_cliente"),
      "nombre" varchar NOT NULL,
      "id_sede" integer REFERENCES "Sedes"("id_sede")
    );
    INSERT INTO "tipo_cliente" ("id_tipo_cliente", "nombre") VALUES (1, 'Particular'), (2, 'Aseguradora')
    ON CONFLICT ("id_tipo_cliente") DO UPDATE SET "nombre" = EXCLUDED."nombre";
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Recuperacion_Clave" (
      "id_recuperacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_usuario" INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario"),
      "codigo" VARCHAR(6) NOT NULL,
      "expiracion" TIMESTAMP NOT NULL,
      "usado" BOOLEAN DEFAULT false,
      "intentos" INTEGER DEFAULT 0,
      "fecha_creacion" TIMESTAMP DEFAULT (now())
    );
  `);
  await pool.query(`ALTER TABLE "Recuperacion_Clave" ADD COLUMN IF NOT EXISTS intentos INTEGER DEFAULT 0`);
  await pool.query(`ALTER TABLE "Recuperacion_Clave" ALTER COLUMN codigo TYPE VARCHAR(60)`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Roles" (
      "id_rol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "nombre" VARCHAR NOT NULL,
      "key" VARCHAR NOT NULL,
      "id_sede" INTEGER REFERENCES "Sedes"("id_sede"),
      "activo" BOOLEAN DEFAULT true,
      "fecha_creacion" TIMESTAMP DEFAULT (now()),
      UNIQUE ("key", "id_sede")
    );
  `);

  const totalRoles = await pool.query('SELECT COUNT(*) as total FROM "Roles"');
  if (Number(totalRoles.rows[0].total) === 0) {
    const sedesExistentes = await pool.query('SELECT id_sede FROM "Sedes"');
    for (const sede of sedesExistentes.rows) {
      await pool.query(`
        INSERT INTO "Roles" ("nombre", "key", "id_sede", "activo") VALUES
          ('ADMINISTRADOR', 'administrador', $1, true),
          ('RECEPCIONISTA', 'recepcionista', $1, true),
          ('MEDICO', 'medico', $1, true),
          ('COORDINADOR', 'coordinador', $1, true),
          ('ANALISTA', 'analista', $1, true),
          ('LABORATORIO', 'laboratorio', $1, true),
          ('IMAGENES', 'imagenes', $1, true),
          ('ENFERMERO', 'enfermero', $1, true)
        ON CONFLICT ("key", "id_sede") DO NOTHING
      `, [sede.id_sede]);
    }
  }

  try {
    await pool.query(`
      UPDATE "Roles" SET nombre = UPPER(TRANSLATE(nombre, 'áéíóúÁÉÍÓÚ', 'aeiouAEIOU'));
      UPDATE "Roles" SET nombre = REPLACE(nombre, ' ', '');
    `);
  } catch (errNorm) {
    logger.warn('Aviso: No se pudieron normalizar nombres de roles', { error: errNorm.message });
  }

  await pool.query('ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS sesion_token VARCHAR DEFAULT NULL');
  await pool.query('ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS id_rol INTEGER REFERENCES "Roles"("id_rol")');

  const checkRolCol = await pool.query("SELECT column_name FROM information_schema.columns WHERE LOWER(table_name) = 'usuarios' AND LOWER(column_name) = 'rol'");
  if (checkRolCol.rowCount > 0) {
    logger.info('Migrando datos de "rol" a "id_rol"...');
    await pool.query('UPDATE "Usuarios" u SET id_rol = r.id_rol FROM "Roles" r WHERE u.rol = r.key AND u.id_rol IS NULL');
    await pool.query('ALTER TABLE "Usuarios" DROP CONSTRAINT IF EXISTS fk_usuarios_rol');
    await pool.query('ALTER TABLE "Usuarios" DROP COLUMN IF EXISTS rol');
  }

  try {
    const apsRole = await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'aps'`);
    if (apsRole.rowCount > 0) {
      const apsId = apsRole.rows[0].id_rol;
      const analistaId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'analista'`)).rows[0].id_rol;
      const coordId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'coordinador'`)).rows[0].id_rol;
      const labId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'laboratorio'`)).rows[0].id_rol;
      const imgId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'imagenes'`)).rows[0].id_rol;

      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query('UPDATE "Usuarios" SET id_rol = $1 WHERE id_rol = $2', [analistaId, apsId]);
        await client.query('DELETE FROM "Roles" WHERE key = $1', ['aps']);
        await client.query('UPDATE "Usuarios" SET id_rol = 4 WHERE id_rol = $1', [coordId]);
        await client.query('UPDATE "Roles" SET id_rol = 4 WHERE key = $1', ['coordinador']);
        await client.query('UPDATE "Usuarios" SET id_rol = 5 WHERE id_rol = $1', [analistaId]);
        await client.query('UPDATE "Roles" SET id_rol = 5 WHERE key = $1', ['analista']);
        await client.query('UPDATE "Usuarios" SET id_rol = 6 WHERE id_rol = $1', [labId]);
        await client.query('UPDATE "Roles" SET id_rol = 6 WHERE key = $1', ['laboratorio']);
        await client.query('UPDATE "Usuarios" SET id_rol = 7 WHERE id_rol = $1', [imgId]);
        await client.query('UPDATE "Roles" SET id_rol = 7 WHERE key = $1', ['imagenes']);
        await client.query('COMMIT');
        logger.info('Rol APS eliminado, usuarios migrados a Analista, IDs reordenados');
      } catch (txErr) {
        await client.query('ROLLBACK');
        logger.error('Error migrando rol APS', { error: txErr.message });
      } finally {
        client.release();
      }
    }
  } catch (apsErr) {
    logger.warn('Error consultando rol APS (probablemente ya migrado)', { error: apsErr.message });
  }

  // Reparar usuarios cuyo id_rol quedó apuntando al rol de OTRA sede: al
  // cambiar la sede de un usuario en Personal, el id_rol se resolvía con la
  // sede del admin que editaba (no con la sede nueva del usuario), dejando
  // id_sede e id_rol de sedes distintas → los permisos del sidebar eran los
  // del rol equivocado. Esto re-sincroniza id_rol con la sede actual de cada
  // usuario (mismo key de rol en su sede). Se corrigió en actualizarPersonal;
  // aquí se reparan los registros ya afectados.
  try {
    const syncRes = await pool.query(`
      UPDATE "Usuarios" u
      SET id_rol = r.id_rol
      FROM "Roles" r
      WHERE u.id_rol IS NOT NULL
        AND u.id_sede IS NOT NULL
        AND r.id_sede = u.id_sede
        AND r.key = (SELECT r3.key FROM "Roles" r3 WHERE r3.id_rol = u.id_rol)
        AND (SELECT r2.id_sede FROM "Roles" r2 WHERE r2.id_rol = u.id_rol) IS DISTINCT FROM u.id_sede
    `);
    if (syncRes.rowCount > 0) {
      logger.info(`Se re-sincronizó el rol de ${syncRes.rowCount} usuario(s) con su sede actual`);
    }
  } catch (syncErr) {
    logger.warn('Aviso: no se pudo re-sincronizar id_rol de usuarios con su sede', { error: syncErr.message });
  }

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Refresh_Tokens" (
      "id_refresh" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_usuario" INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario"),
      "token_hash" VARCHAR NOT NULL,
      "expira" TIMESTAMP,
      "revocado" BOOLEAN DEFAULT false,
      "fecha_creacion" TIMESTAMP DEFAULT (now())
    );
  `);
  await pool.query('CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON "Refresh_Tokens"("token_hash")');
  await pool.query('ALTER TABLE "Refresh_Tokens" ALTER COLUMN "expira" DROP NOT NULL');

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Audit_Log" (
      "id_audit" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_usuario" INTEGER REFERENCES "Usuarios"("id_usuario"),
      "accion" VARCHAR NOT NULL,
      "recurso" VARCHAR,
      "id_recurso_afectado" INTEGER,
      "detalle" JSONB,
      "ip" VARCHAR,
      "fecha" TIMESTAMP DEFAULT (now())
    );
  `);
  await pool.query('CREATE INDEX IF NOT EXISTS idx_audit_log_fecha ON "Audit_Log"("fecha")');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_audit_log_accion ON "Audit_Log"("accion")');

  // ====================================================================
  // Numeración atómica de turnos por día
  // ====================================================================
  // El método anterior calculaba el número con COUNT(*) + 1 de las atenciones
  // del día: si se borraba una atención, el conteo bajaba y el número se
  // reciclaba (números duplicados), y dos registros simultáneos podían
  // obtener el mismo número. La secuencia por día (sede + servicio) se
  // incrementa dentro de la misma transacción del turno: es imposible
  // que dos turnos repitan número, incluso con concurrencia o borrados.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Secuencia_Turnos" (
      "id_sede" INTEGER NOT NULL REFERENCES "Sedes"("id_sede"),
      "id_servicio" INTEGER NOT NULL REFERENCES "Servicio"("id_servicio"),
      "fecha" DATE NOT NULL,
      "ultimo" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("id_sede", "id_servicio", "fecha")
    );
  `);

  // Sembrar el contador de HOY con el máximo existente (para no repetir números)
  await pool.query(`
    INSERT INTO "Secuencia_Turnos" ("id_sede", "id_servicio", "fecha", "ultimo")
    SELECT a.id_sede, a.id_servicio, CURRENT_DATE,
           MAX(NULLIF(regexp_replace(a.numero, '[^0-9]', '', 'g'), '')::int)
    FROM "Atencion" a
    WHERE a.hora_llegada >= CURRENT_DATE AND a.numero ~ '[0-9]'
    GROUP BY a.id_sede, a.id_servicio
    ON CONFLICT ("id_sede", "id_servicio", "fecha") DO NOTHING
  `);

  // Corregir duplicados de HOY: la atención más antigua conserva el número y
  // las posteriores se renumeran al final de la secuencia del día.
  const atencionesHoy = await pool.query(`
    SELECT a.id_atencion, a.id_sede, a.id_servicio, a.numero
    FROM "Atencion" a
    WHERE a.hora_llegada >= CURRENT_DATE
    ORDER BY a.id_sede, a.id_servicio, a.numero, a.id_atencion
  `);
  const maxPorGrupo = new Map();
  for (const f of atencionesHoy.rows) {
    const grupo = `${f.id_sede}|${f.id_servicio}`;
    const num = parseInt(String(f.numero).replace(/[^0-9]/g, ''), 10) || 0;
    maxPorGrupo.set(grupo, Math.max(maxPorGrupo.get(grupo) || 0, num));
  }
  const vistos = new Map();
  for (const f of atencionesHoy.rows) {
    const clave = `${f.id_sede}|${f.id_servicio}|${f.numero}`;
    const veces = (vistos.get(clave) || 0) + 1;
    vistos.set(clave, veces);
    if (veces > 1) {
      const grupo = `${f.id_sede}|${f.id_servicio}`;
      const siguiente = (maxPorGrupo.get(grupo) || 0) + 1;
      maxPorGrupo.set(grupo, siguiente);
      const nuevoNumero = String(f.numero).replace(/[0-9]+$/, String(siguiente).padStart(2, '0'));
      await pool.query('UPDATE "Atencion" SET numero = $1 WHERE id_atencion = $2', [nuevoNumero, f.id_atencion]);
      logger.info(`Turno duplicado corregido: atención #${f.id_atencion} ahora es ${nuevoNumero}`);
    }
  }

  // Sincronizar el contador con el máximo tras cualquier renumeración
  await pool.query(`
    UPDATE "Secuencia_Turnos" s SET ultimo = sub.mx
    FROM (
      SELECT a.id_sede, a.id_servicio,
             MAX(NULLIF(regexp_replace(a.numero, '[^0-9]', '', 'g'), '')::int) as mx
      FROM "Atencion" a
      WHERE a.hora_llegada >= CURRENT_DATE AND a.numero ~ '[0-9]'
      GROUP BY a.id_sede, a.id_servicio
    ) sub
    WHERE s.id_sede = sub.id_sede AND s.id_servicio = sub.id_servicio AND s.fecha = CURRENT_DATE
  `);

  // Índice de apoyo para las consultas de turnos del día
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_atencion_sede_servicio_numero
    ON "Atencion" ("id_sede", "id_servicio", "numero")
  `);

  // Índice para el reporte diario: las subconsultas del historial (estados
  // 5, 6, 7, 9) usan (id_atencion, id_estado) y la FK no crea índice solo.
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_historial_atencion_estado
    ON "Historial_Atencion" ("id_atencion", "id_estado")
  `);

  // Permisos de APS / Laboratorio / Imágenes: estos módulos ven, editan y
  // retiran pacientes (eliminar = retirar), pero NO crean (eso es de admisión).
  // Se otorgan ver/editar/eliminar (+marcar_ausente en APS para que el retiro
  // funcione en el backend) y se elimina la acción 'crear' de esos módulos.
  // Idempotente (ON CONFLICT DO NOTHING).
  try {
    await pool.query(`
      DO $$
      DECLARE
        v_id_rol INT;
        v_id_rec INT;
        v_id_acc INT;
        sede RECORD;
        asignacion RECORD;
        acciones TEXT[];
        accion TEXT;
      BEGIN
        FOR sede IN SELECT id_sede FROM "Sedes" LOOP
          FOR asignacion IN
            SELECT 'aps' AS recurso, rol_key
            FROM (VALUES ('analista'), ('coordinador'), ('administrador')) AS r(rol_key)
            UNION ALL
            SELECT 'laboratorio', rol_key
            FROM (VALUES ('laboratorio'), ('administrador')) AS r(rol_key)
            UNION ALL
            SELECT 'imagenes', rol_key
            FROM (VALUES ('imagenes'), ('administrador')) AS r(rol_key)
          LOOP
            SELECT id_recurso INTO v_id_rec FROM "Recursos" WHERE key = asignacion.recurso;
            IF v_id_rec IS NULL THEN
              INSERT INTO "Recursos" (key, nombre) VALUES (asignacion.recurso, asignacion.recurso)
              ON CONFLICT (key) DO UPDATE SET key = EXCLUDED.key
              RETURNING id_recurso INTO v_id_rec;
            END IF;
            SELECT id_rol INTO v_id_rol FROM "Roles" WHERE key = asignacion.rol_key AND id_sede = sede.id_sede;
            IF v_id_rol IS NOT NULL AND v_id_rec IS NOT NULL THEN
              IF asignacion.recurso = 'aps' THEN
                acciones := ARRAY['ver', 'editar', 'eliminar', 'marcar_ausente'];
              ELSE
                acciones := ARRAY['ver', 'editar', 'eliminar'];
              END IF;
              FOREACH accion IN ARRAY acciones LOOP
                SELECT id_accion INTO v_id_acc FROM "Acciones" WHERE key = accion;
                IF v_id_acc IS NULL THEN
                  INSERT INTO "Acciones" (key, nombre) VALUES (accion, accion)
                  ON CONFLICT (key) DO UPDATE SET key = EXCLUDED.key
                  RETURNING id_accion INTO v_id_acc;
                END IF;
                INSERT INTO "Roles_Recursos_Acciones" (id_rol, id_recurso, id_accion)
                VALUES (v_id_rol, v_id_rec, v_id_acc) ON CONFLICT DO NOTHING;
              END LOOP;
            END IF;
          END LOOP;
        END LOOP;

        -- APS / Laboratorio / Imágenes no crean pacientes: quitar 'crear'.
        DELETE FROM "Roles_Recursos_Acciones" rra
        USING "Roles" r, "Recursos" rec, "Acciones" acc
        WHERE rra.id_rol = r.id_rol
          AND rra.id_recurso = rec.id_recurso
          AND rra.id_accion = acc.id_accion
          AND rec.key IN ('aps', 'laboratorio', 'imagenes')
          AND acc.key = 'crear';
      END $$;
    `);
  } catch (errPerm) {
    logger.warn('Aviso: no se pudieron actualizar los permisos de los roles operativos', { error: errPerm.message });
  }

  // ====================================================================
  // MÚLTIPLES ESPECIALIDADES POR MÉDICO (tabla puente N:M)
  // ====================================================================
  // Un médico puede tener varias especialidades. "Usuario_Especialidad"
  // guarda la relación N:M; "Usuarios.id_especialidad" se mantiene como la
  // especialidad PRINCIPAL (login, turnero y notificaciones la siguen usando).
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS "Usuario_Especialidad" (
        "id_usuario" INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario") ON DELETE CASCADE,
        "id_especialidad" INTEGER NOT NULL REFERENCES "Especialidades"("id_especialidad") ON DELETE CASCADE,
        "activo" BOOLEAN NOT NULL DEFAULT TRUE,
        PRIMARY KEY ("id_usuario", "id_especialidad")
      )
    `);
    // Para instalaciones existentes: agrega la columna si no existe
    await pool.query(`
      ALTER TABLE "Usuario_Especialidad" ADD COLUMN IF NOT EXISTS "activo" BOOLEAN NOT NULL DEFAULT TRUE
    `);
    // Consultorio POR especialidad del médico (un médico puede atender cada
    // especialidad en un consultorio distinto). NULL = aún sin asignar.
    await pool.query(`
      ALTER TABLE "Usuario_Especialidad" ADD COLUMN IF NOT EXISTS "id_consultorio" INTEGER REFERENCES "Consultorios"("id_consultorio") ON DELETE SET NULL
    `);
    // Migrar lo existente: la especialidad actual de cada usuario pasa a la tabla
    await pool.query(`
      INSERT INTO "Usuario_Especialidad" ("id_usuario", "id_especialidad")
      SELECT u.id_usuario, u.id_especialidad FROM "Usuarios" u
      WHERE u.id_especialidad IS NOT NULL
      ON CONFLICT DO NOTHING
    `);
    // Lo ya existente queda activo por defecto (la columna default TRUE)
    await pool.query(`
      UPDATE "Usuario_Especialidad" SET "activo" = TRUE WHERE "activo" IS NULL
    `);
  } catch (errEsp) {
    logger.warn('Aviso: no se pudo crear la tabla de especialidades por médico', { error: errEsp.message });
  }

  // --- Roles múltiples por usuario ---
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS "Usuario_Rol" (
        id_usuario INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario") ON DELETE CASCADE,
        id_rol INTEGER NOT NULL REFERENCES "Roles"("id_rol") ON DELETE CASCADE,
        PRIMARY KEY (id_usuario, id_rol)
      )
    `);
    // Migrar id_rol actual a la nueva tabla (solo si no tiene registros)
    const countResult = await pool.query('SELECT COUNT(*)::int AS cnt FROM "Usuario_Rol"');
    if (countResult.rows[0].cnt === 0) {
      await pool.query(`
        INSERT INTO "Usuario_Rol" (id_usuario, id_rol)
        SELECT id_usuario, id_rol FROM "Usuarios" WHERE id_rol IS NOT NULL
        ON CONFLICT DO NOTHING
      `);
      logger.info('Migrados roles existentes a Usuario_Rol');
    }
  } catch (errRol) {
    logger.warn('Aviso: no se pudo crear la tabla Usuario_Rol', { error: errRol.message });
  }

  logger.info('Base de datos inicializada correctamente');
};

if (require.main === module) {
  runMigrations()
    .then(() => process.exit(0))
    .catch((err) => {
      logger.error('Error en migraciones', { error: err.message });
      process.exit(1);
    });
}

module.exports = { runMigrations };
