const pool = require('./src/config/db');
const logger = require('./src/config/logger');

const runMigrations = async () => {
  logger.info('Ejecutando migraciones...');

  await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_consultorio INTEGER REFERENCES "Consultorios"("id_consultorio")');
  await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_cliente INTEGER REFERENCES "cliente"("id_cliente")');
  await pool.query('ALTER TABLE "Atencion" ADD COLUMN IF NOT EXISTS id_medico INTEGER REFERENCES "Usuarios"("id_usuario")');

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "tipo_cliente" (
      "id_tipo_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "nombre" varchar NOT NULL
    );
    CREATE TABLE IF NOT EXISTS "cliente" (
      "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_tipo_cliente" integer NOT NULL REFERENCES "tipo_cliente"("id_tipo_cliente"),
      "nombre" varchar NOT NULL,
      "id_sede" integer REFERENCES "Sedes"("id_sede")
    );
    INSERT INTO "tipo_cliente" ("id_tipo_cliente", "nombre") VALUES (1, 'Particular'), (2, 'Aseguradora')
    ON CONFLICT ("id_tipo_cliente") DO UPDATE SET "nombre" = EXCLUDED."nombre";
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Recuperacion_Clave" (
      "id_recuperacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_usuario" INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario"),
      "codigo" VARCHAR(6) NOT NULL,
      "expiracion" TIMESTAMP NOT NULL,
      "usado" BOOLEAN DEFAULT false,
      "intentos" INTEGER DEFAULT 0,
      "fecha_creacion" TIMESTAMP DEFAULT (now())
    );
  `);
  await pool.query(`ALTER TABLE "Recuperacion_Clave" ADD COLUMN IF NOT EXISTS intentos INTEGER DEFAULT 0`);
  await pool.query(`ALTER TABLE "Recuperacion_Clave" ALTER COLUMN codigo TYPE VARCHAR(60)`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Roles" (
      "id_rol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "nombre" VARCHAR NOT NULL,
      "key" VARCHAR NOT NULL,
      "id_sede" INTEGER REFERENCES "Sedes"("id_sede"),
      "activo" BOOLEAN DEFAULT true,
      "fecha_creacion" TIMESTAMP DEFAULT (now()),
      UNIQUE ("key", "id_sede")
    );
  `);

  const totalRoles = await pool.query('SELECT COUNT(*) as total FROM "Roles"');
  if (Number(totalRoles.rows[0].total) === 0) {
    const sedesExistentes = await pool.query('SELECT id_sede FROM "Sedes"');
    for (const sede of sedesExistentes.rows) {
      await pool.query(`
        INSERT INTO "Roles" ("nombre", "key", "id_sede", "activo") VALUES
          ('ADMINISTRADOR', 'administrador', $1, true),
          ('RECEPCIONISTA', 'recepcionista', $1, true),
          ('MEDICO', 'medico', $1, true),
          ('COORDINADOR', 'coordinador', $1, true),
          ('ANALISTA', 'analista', $1, true),
          ('LABORATORIO', 'laboratorio', $1, true),
          ('IMAGENES', 'imagenes', $1, true),
          ('ENFERMERO', 'enfermero', $1, true)
        ON CONFLICT ("key", "id_sede") DO NOTHING
      `, [sede.id_sede]);
    }
  }

  try {
    await pool.query(`
      UPDATE "Roles" SET nombre = UPPER(TRANSLATE(nombre, 'áéíóúÁÉÍÓÚ', 'aeiouAEIOU'));
      UPDATE "Roles" SET nombre = REPLACE(nombre, ' ', '');
    `);
  } catch (errNorm) {
    logger.warn('Aviso: No se pudieron normalizar nombres de roles', { error: errNorm.message });
  }

  await pool.query('ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS sesion_token VARCHAR DEFAULT NULL');
  await pool.query('ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS id_rol INTEGER REFERENCES "Roles"("id_rol")');

  const checkRolCol = await pool.query("SELECT column_name FROM information_schema.columns WHERE LOWER(table_name) = 'usuarios' AND LOWER(column_name) = 'rol'");
  if (checkRolCol.rowCount > 0) {
    logger.info('Migrando datos de "rol" a "id_rol"...');
    await pool.query('UPDATE "Usuarios" u SET id_rol = r.id_rol FROM "Roles" r WHERE u.rol = r.key AND u.id_rol IS NULL');
    await pool.query('ALTER TABLE "Usuarios" DROP CONSTRAINT IF EXISTS fk_usuarios_rol');
    await pool.query('ALTER TABLE "Usuarios" DROP COLUMN IF EXISTS rol');
  }

  try {
    const apsRole = await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'aps'`);
    if (apsRole.rowCount > 0) {
      const apsId = apsRole.rows[0].id_rol;
      const analistaId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'analista'`)).rows[0].id_rol;
      const coordId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'coordinador'`)).rows[0].id_rol;
      const labId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'laboratorio'`)).rows[0].id_rol;
      const imgId = (await pool.query(`SELECT id_rol FROM "Roles" WHERE key = 'imagenes'`)).rows[0].id_rol;

      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query('UPDATE "Usuarios" SET id_rol = $1 WHERE id_rol = $2', [analistaId, apsId]);
        await client.query('DELETE FROM "Roles" WHERE key = $1', ['aps']);
        await client.query('UPDATE "Usuarios" SET id_rol = 4 WHERE id_rol = $1', [coordId]);
        await client.query('UPDATE "Roles" SET id_rol = 4 WHERE key = $1', ['coordinador']);
        await client.query('UPDATE "Usuarios" SET id_rol = 5 WHERE id_rol = $1', [analistaId]);
        await client.query('UPDATE "Roles" SET id_rol = 5 WHERE key = $1', ['analista']);
        await client.query('UPDATE "Usuarios" SET id_rol = 6 WHERE id_rol = $1', [labId]);
        await client.query('UPDATE "Roles" SET id_rol = 6 WHERE key = $1', ['laboratorio']);
        await client.query('UPDATE "Usuarios" SET id_rol = 7 WHERE id_rol = $1', [imgId]);
        await client.query('UPDATE "Roles" SET id_rol = 7 WHERE key = $1', ['imagenes']);
        await client.query('COMMIT');
        logger.info('Rol APS eliminado, usuarios migrados a Analista, IDs reordenados');
      } catch (txErr) {
        await client.query('ROLLBACK');
        logger.error('Error migrando rol APS', { error: txErr.message });
      } finally {
        client.release();
      }
    }
  } catch (apsErr) {
    logger.warn('Error consultando rol APS (probablemente ya migrado)', { error: apsErr.message });
  }

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Refresh_Tokens" (
      "id_refresh" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_usuario" INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario"),
      "token_hash" VARCHAR NOT NULL,
      "expira" TIMESTAMP NOT NULL,
      "revocado" BOOLEAN DEFAULT false,
      "fecha_creacion" TIMESTAMP DEFAULT (now())
    );
  `);
  await pool.query('CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON "Refresh_Tokens"("token_hash")');

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "Audit_Log" (
      "id_audit" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "id_usuario" INTEGER REFERENCES "Usuarios"("id_usuario"),
      "accion" VARCHAR NOT NULL,
      "recurso" VARCHAR,
      "id_recurso_afectado" INTEGER,
      "detalle" JSONB,
      "ip" VARCHAR,
      "fecha" TIMESTAMP DEFAULT (now())
    );
  `);
  await pool.query('CREATE INDEX IF NOT EXISTS idx_audit_log_fecha ON "Audit_Log"("fecha")');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_audit_log_accion ON "Audit_Log"("accion")');

  logger.info('Base de datos inicializada correctamente');
};

if (require.main === module) {
  runMigrations()
    .then(() => process.exit(0))
    .catch((err) => {
      logger.error('Error en migraciones', { error: err.message });
      process.exit(1);
    });
}

module.exports = { runMigrations };
