-- ======================================================
-- ESTRUCTURA RESTAURADA CON SOPORTE PARA SEDES
-- ======================================================

DROP TABLE IF EXISTS "Historial_Atencion" CASCADE;
DROP TABLE IF EXISTS "Atencion" CASCADE;
DROP TABLE IF EXISTS "Pacientes" CASCADE;
DROP TABLE IF EXISTS "Usuarios" CASCADE;
DROP TABLE IF EXISTS "Consultorios" CASCADE;
DROP TABLE IF EXISTS "Servicio" CASCADE;
DROP TABLE IF EXISTS "Responsable_Pago" CASCADE;
DROP TABLE IF EXISTS "Estado" CASCADE;
DROP TABLE IF EXISTS "Sedes" CASCADE;
DROP TABLE IF EXISTS "turnos" CASCADE;

-- TABLA DE SEDES
CREATE TABLE "Sedes" (
  "id_sede" INTEGER PRIMARY KEY,
  "nombre" varchar NOT NULL
);

-- TABLA DE SERVICIOS
CREATE TABLE "Servicio" (
  "id_servicio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_servicio" varchar NOT NULL,
  "prefijo" varchar(5),
  "status" boolean DEFAULT true,
  "piso" varchar,
  "consultorio" varchar,
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE TABLE "Responsable_Pago" (
  "id_responsable" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "status" boolean DEFAULT true
);

CREATE TABLE "Estado" (
  "id_estado" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_estado" varchar NOT NULL
);

CREATE TABLE "Consultorios" (
  "id_consultorio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "piso" varchar,
  "id_servicio" integer REFERENCES "Servicio"("id_servicio"),
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "estado_fisico" varchar DEFAULT 'LIBRE'
);

CREATE TABLE "Usuarios" (
  "id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cedula" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "rol" varchar NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "telefono" varchar,
  "email" varchar UNIQUE,
  "piso" integer,
  "id_consultorio" integer REFERENCES "Consultorios"("id_consultorio"),
  "id_servicio" integer REFERENCES "Servicio"("id_servicio"),
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "status" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE TABLE "Pacientes" (
  "id_paciente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cedula" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "telefono" varchar,
  "email" varchar,
  "notificaciones_sms" boolean DEFAULT true,
  "status" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (now())
);

-- Tabla turnos (usada en el seed antiguo)
CREATE TABLE "turnos" (
  "id" SERIAL PRIMARY KEY,
  "nombre_paciente" varchar,
  "documento_paciente" varchar,
  "telefono_paciente" varchar,
  "servicio_id" integer,
  "id_sede" integer,
  "estado" varchar,
  "numero" varchar,
  "hora_llegada" timestamp,
  "hora_inicio" timestamp,
  "hora_fin" timestamp
);

CREATE TABLE "Atencion" (
  "id_atencion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" integer REFERENCES "Pacientes"("id_paciente"),
  "id_servicio" integer REFERENCES "Servicio"("id_servicio"),
  "id_responsable" integer REFERENCES "Responsable_Pago"("id_responsable"),
  "id_estado_actual" integer REFERENCES "Estado"("id_estado"),
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "hora_llegada" timestamp DEFAULT (now()),
  "hora_salida" timestamp,
  "id_usuario_registro" integer REFERENCES "Usuarios"("id_usuario")
);

CREATE TABLE "Historial_Atencion" (
  "id_historial" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_atencion" integer REFERENCES "Atencion"("id_atencion"),
  "id_estado" integer REFERENCES "Estado"("id_estado"),
  "fecha_hora" timestamp DEFAULT (now())
);
