-- ======================================================
-- ESQUEMA COMPLETO DE LA BASE DE DATOS
-- Generado desde la base de datos actual
-- ======================================================

-- ELIMINAR TABLAS EXISTENTES (orden inverso de dependencias)
DROP TABLE IF EXISTS "Historial_Atencion" CASCADE;
DROP TABLE IF EXISTS "Especialidad_Consultorio" CASCADE;
DROP TABLE IF EXISTS "Atencion" CASCADE;
DROP TABLE IF EXISTS "Pacientes" CASCADE;
DROP TABLE IF EXISTS "Usuarios" CASCADE;
DROP TABLE IF EXISTS "Roles" CASCADE;
DROP TABLE IF EXISTS "Especialidades" CASCADE;
DROP TABLE IF EXISTS "Consultorios" CASCADE;
DROP TABLE IF EXISTS "Servicio" CASCADE;
DROP TABLE IF EXISTS "Responsable_Pago" CASCADE;
DROP TABLE IF EXISTS "Estado" CASCADE;
DROP TABLE IF EXISTS "Sedes" CASCADE;
DROP TABLE IF EXISTS "cliente" CASCADE;
DROP TABLE IF EXISTS "tipo_cliente" CASCADE;
DROP TABLE IF EXISTS "Roles_Permisos" CASCADE;
DROP TABLE IF EXISTS "Permisos" CASCADE;
DROP TABLE IF EXISTS "Recuperacion_Clave" CASCADE;
DROP TABLE IF EXISTS "turnos" CASCADE;

-- ======================================================
-- CREACION DE TABLAS (orden respetando FKs)
-- ======================================================

-- SEDES
CREATE TABLE "Sedes" (
  "id_sede" INTEGER PRIMARY KEY,
  "nombre" varchar NOT NULL
);

-- SERVICIOS
CREATE TABLE "Servicio" (
  "id_servicio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_servicio" varchar NOT NULL,
  "prefijo" varchar(5),
  "status" boolean DEFAULT true,
  "piso" varchar,
  "consultorio" varchar,
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "fecha_creacion" timestamp DEFAULT (now())
);

-- TIPO CLIENTE
CREATE TABLE "tipo_cliente" (
  "id_tipo_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL
);

-- CLIENTES / ASEGURADORAS
CREATE TABLE "cliente" (
  "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_tipo_cliente" integer NOT NULL REFERENCES "tipo_cliente"("id_tipo_cliente"),
  "nombre" varchar NOT NULL,
  "id_sede" integer REFERENCES "Sedes"("id_sede")
);

-- RESPONSABLE DE PAGO
CREATE TABLE "Responsable_Pago" (
  "id_responsable" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "status" boolean DEFAULT true
);

-- ESTADOS
CREATE TABLE "Estado" (
  "id_estado" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_estado" varchar NOT NULL
);

-- CONSULTORIOS
CREATE TABLE "Consultorios" (
  "id_consultorio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "piso" varchar,
  "id_servicio" integer REFERENCES "Servicio"("id_servicio"),
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "estado_fisico" varchar DEFAULT 'LIBRE'
);

-- ESPECIALIDADES
CREATE TABLE "Especialidades" (
  "id_especialidad" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "prefijo" varchar(10),
  "id_servicio" integer REFERENCES "Servicio"("id_servicio"),
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "piso" varchar,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (now()),
  "id_consultorio" integer REFERENCES "Consultorios"("id_consultorio")
);

-- ROLES
CREATE TABLE "Roles" (
  "id_rol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "key" varchar UNIQUE NOT NULL,
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (now())
);

-- RECURSOS
CREATE TABLE "Recursos" (
  "id_recurso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "descripcion" varchar,
  "fecha_creacion" timestamp DEFAULT (now())
);

-- ACCIONES
CREATE TABLE "Acciones" (
  "id_accion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "descripcion" varchar,
  "fecha_creacion" timestamp DEFAULT (now())
);

-- ROLES <-> RECURSOS <-> ACCIONES
CREATE TABLE "Roles_Recursos_Acciones" (
  "id_rol" integer NOT NULL REFERENCES "Roles"("id_rol") ON DELETE CASCADE,
  "id_recurso" integer NOT NULL REFERENCES "Recursos"("id_recurso") ON DELETE CASCADE,
  "id_accion" integer NOT NULL REFERENCES "Acciones"("id_accion") ON DELETE CASCADE,
  PRIMARY KEY ("id_rol", "id_recurso", "id_accion")
);

-- USUARIOS
CREATE TABLE "Usuarios" (
  "id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cedula" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "id_rol" integer NOT NULL REFERENCES "Roles"("id_rol"),
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "email" varchar,
  "telefono" varchar,
  "piso" varchar,
  "id_consultorio" integer REFERENCES "Consultorios"("id_consultorio"),
  "id_servicio" integer REFERENCES "Servicio"("id_servicio"),
  "id_especialidad" integer REFERENCES "Especialidades"("id_especialidad"),
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "status" boolean DEFAULT true,
  "fecha_creacion" timestamp DEFAULT (now())
);

-- PACIENTES
CREATE TABLE "Pacientes" (
  "id_paciente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cedula" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "telefono" varchar,
  "status" boolean DEFAULT true,
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "fecha_creacion" timestamp DEFAULT (now())
);

-- ATENCION / TURNOS
CREATE TABLE "Atencion" (
  "id_atencion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" integer REFERENCES "Pacientes"("id_paciente"),
  "id_servicio" integer REFERENCES "Servicio"("id_servicio"),
  "id_especialidad" integer REFERENCES "Especialidades"("id_especialidad"),
  "id_responsable" integer REFERENCES "Responsable_Pago"("id_responsable"),
  "id_estado_actual" integer REFERENCES "Estado"("id_estado"),
  "id_sede" integer REFERENCES "Sedes"("id_sede"),
  "hora_llegada" timestamp DEFAULT (now()),
  "hora_salida" timestamp,
  "id_usuario_registro" integer REFERENCES "Usuarios"("id_usuario"),
  "id_consultorio" integer REFERENCES "Consultorios"("id_consultorio"),
  "numero" VARCHAR(20),
  "id_cliente" integer REFERENCES "cliente"("id_cliente")
);

-- JUNCTION: ESPECIALIDAD <-> CONSULTORIO
CREATE TABLE "Especialidad_Consultorio" (
  "id_especialidad" INTEGER NOT NULL REFERENCES "Especialidades"("id_especialidad") ON DELETE CASCADE,
  "id_consultorio" INTEGER NOT NULL REFERENCES "Consultorios"("id_consultorio") ON DELETE CASCADE,
  PRIMARY KEY ("id_especialidad", "id_consultorio")
);

-- HISTORIAL DE ATENCIONES
CREATE TABLE "Historial_Atencion" (
  "id_historial" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_atencion" integer REFERENCES "Atencion"("id_atencion"),
  "id_estado" integer REFERENCES "Estado"("id_estado"),
  "fecha_hora" timestamp DEFAULT (now())
);

-- RECUPERACION DE CLAVE (OTP)
CREATE TABLE "Recuperacion_Clave" (
  "id_recuperacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario"),
  "codigo" VARCHAR(6) NOT NULL,
  "expiracion" TIMESTAMP NOT NULL,
  "usado" BOOLEAN DEFAULT false,
  "fecha_creacion" TIMESTAMP DEFAULT (now())
);

-- ======================================================
-- DATOS INICIALES
-- ======================================================

-- SEDES
INSERT INTO "Sedes" ("id_sede", "nombre") VALUES
  (1, 'Plaza Sucre'),
  (2, 'Santa Mónica');

-- SERVICIOS
INSERT INTO "Servicio" ("id_servicio", "nombre_servicio", "prefijo", "status", "id_sede") VALUES
  (1, 'CONSULTA', 'CONS', true, 1),
  (2, 'LABORATORIO', 'LAB', true, 1),
  (3, 'IMAGENES', 'IMG', true, 1);

-- TIPO CLIENTE
INSERT INTO "tipo_cliente" ("id_tipo_cliente", "nombre") VALUES
  (1, 'Particular'),
  (2, 'Aseguradora');

-- CLIENTES / ASEGURADORAS
INSERT INTO "cliente" ("id_cliente", "id_tipo_cliente", "nombre", "id_sede") VALUES
  (1, 2, 'SEGUROS MIRANDA', 1),
  (2, 2, 'SEGUROS CARACAS', 1);

-- RESPONSABLE DE PAGO
INSERT INTO "Responsable_Pago" ("id_responsable", "nombre") VALUES
  (1, 'Particular'),
  (2, 'Seguro');

-- ESTADOS
INSERT INTO "Estado" ("id_estado", "nombre_estado") VALUES
  (1, 'Registrado'),
  (2, 'En Caja'),
  (3, 'Sala de Espera'),
  (4, 'Llamado'),
  (5, 'En Atencion'),
  (6, 'Atendido'),
  (7, 'Ausente'),
  (8, 'Espera de clave');

-- CONSULTORIOS
INSERT INTO "Consultorios" ("id_consultorio", "nombre", "piso", "id_servicio", "id_sede", "estado_fisico") VALUES
  (1, '01', '1', 1, 1, 'LIBRE'),
  (2, '02', '1', 1, 1, 'LIBRE'),
  (3, '05', '1', 1, 1, 'LIBRE'),
  (4, '03', '5', 1, 1, 'LIBRE'),
  (5, '10', NULL, 1, 1, 'LIBRE'),
  (6, '06', NULL, 1, 1, 'LIBRE'),
  (7, '20', NULL, 1, 1, 'LIBRE'),
  (8, '16', NULL, 1, 1, 'LIBRE'),
  (9, '11', NULL, 1, 1, 'LIBRE'),
  (10, '08', NULL, 1, 1, 'LIBRE'),
  (11, '17', NULL, 1, 1, 'LIBRE'),
  (12, '12', NULL, 1, 1, 'LIBRE'),
  (13, '15', NULL, 1, 1, 'LIBRE'),
  (14, '14', NULL, 1, 1, 'LIBRE'),
  (15, '13', NULL, 1, 1, 'LIBRE'),
  (16, '19', NULL, 1, 1, 'LIBRE'),
  (17, '07', NULL, 1, 1, 'LIBRE'),
  (18, '18', NULL, 1, 1, 'LIBRE'),
  (19, '04', NULL, 1, 1, 'LIBRE'),
  (20, '09', NULL, 1, 1, 'LIBRE');

-- ESPECIALIDADES
INSERT INTO "Especialidades" ("id_especialidad", "nombre", "prefijo", "id_servicio", "id_sede", "piso", "activo") VALUES
  (4, 'CARDIOLOGIA', 'CARD', 1, 1, '1', true),
  (5, 'PEDIATRIA', 'PED', 1, 1, '1', true),
  (6, 'MEDICINA GENERAL', 'MEDG', 1, 1, '1', true),
  (7, 'OFTALMOLOGIA', 'OFT', 1, 1, '2', true),
  (8, 'GINECOLOGIA', 'GIN', 1, 1, '5', true);

-- JUNCTION: ESPECIALIDAD <-> CONSULTORIO
INSERT INTO "Especialidad_Consultorio" ("id_especialidad", "id_consultorio") VALUES
  (4, 2), (4, 3), (4, 4),
  (5, 1),
  (6, 4),
  (7, 2),
  (8, 3);

-- ROLES
INSERT INTO "Roles" ("nombre", "key", "id_sede", "activo") VALUES
  ('ADMINISTRADOR', 'administrador', NULL, true),
  ('RECEPCIONISTA', 'recepcionista', NULL, true),
  ('MEDICO', 'medico', NULL, true),
  ('COORDINADOR', 'coordinador', NULL, true),
  ('ANALISTA', 'analista', NULL, true),
  ('LABORATORIO', 'laboratorio', NULL, true),
  ('IMAGENES', 'imagenes', NULL, true),
  ('ENFERMERO', 'enfermero', NULL, true);

-- RECURSOS (Módulos/Secciones)
INSERT INTO "Recursos" ("key", "nombre", "descripcion") VALUES
  ('personal', 'Personal', 'Gestión de personal de la clínica'),
  ('roles', 'Roles', 'Gestión de roles del sistema'),
  ('especialidades', 'Especialidades', 'Gestión de especialidades médicas'),
  ('admision', 'Admisión', 'Admisión y registro de pacientes'),
  ('aps', 'APS', 'Atención Primaria en Salud'),
  ('aseguradoras', 'Aseguradoras', 'Gestión de aseguradoras y claves'),
  ('laboratorio', 'Laboratorio', 'Módulo de laboratorio clínico'),
  ('imagenes', 'Imágenes', 'Módulo de imágenes médicas'),
  ('atencion_medica', 'Atención Médica', 'Consulta médica y atención'),
  ('llamado', 'Llamado', 'Llamado de pacientes a sala'),
  ('admin', 'Administración', 'Panel general de administración'),
  ('reportes', 'Reportes', 'Dashboard y reportes estadísticos'),
  ('permisologia', 'Permisología', 'Gestión de permisos'),
  ('sedes', 'Sedes', 'Gestión de sedes'),
  ('servicios', 'Servicios', 'Gestión de servicios de la clínica'),
  ('*', 'Global/Multi-módulo', 'Recurso global comodín');

-- ACCIONES (Operaciones disponibles)
INSERT INTO "Acciones" ("key", "nombre", "descripcion") VALUES
  ('ver', 'Ver', 'Visualizar o listar registros'),
  ('crear', 'Crear', 'Crear o registrar nuevos elementos'),
  ('editar', 'Editar', 'Modificar elementos existentes'),
  ('eliminar', 'Eliminar', 'Dar de baja o borrar registros'),
  ('asignar_turno', 'Asignar Turno', 'Asignar turno de atención'),
  ('enviar_presupuesto', 'Enviar Presupuesto', 'Enviar a presupuesto en APS'),
  ('solicitar_clave', 'Solicitar Clave', 'Solicitar clave a aseguradoras'),
  ('enviar_sala_espera', 'Enviar Sala Espera', 'Mover a sala de espera'),
  ('aprobar_clave', 'Aprobar Clave', 'Aprobar clave de aseguradora'),
  ('reincorporar', 'Reincorporar', 'Reincorporar paciente a cola'),
  ('registrar_caja', 'Registrar Caja', 'Procesar pago/caja'),
  ('pasar_sala_espera', 'Pasar Sala Espera', 'Mover de caja a sala de espera'),
  ('marcar_ausente', 'Marcar Ausente', 'Marcar paciente como ausente'),
  ('laboratorio', 'Llamado Laboratorio', 'Llamar pacientes de laboratorio'),
  ('imagenes', 'Llamado Imágenes', 'Llamar pacientes de imágenes'),
  ('importar_excel', 'Importar Excel', 'Importar desde archivo Excel'),
  ('llamar_siguiente', 'Llamar Siguiente', 'Llamar siguiente turno'),
  ('liberar_consultorio', 'Liberar Consultorio', 'Liberar consultorio manual'),
  ('iniciar', 'Iniciar', 'Iniciar atención médica'),
  ('finalizar', 'Finalizar', 'Finalizar atención médica'),
  ('gestionar_permisos', 'Gestionar Permisos', 'Gestionar matriz de permisos'),
  ('gestionar', 'Gestionar', 'Gestionar CRUD general'),
  ('panel', 'Acceso Panel', 'Acceso al panel principal'),
  ('*', 'Todas las Acciones / Acceso Total', 'Acceso total o comodín');

-- ROLES <-> RECURSOS <-> ACCIONES (Asignación)
CREATE OR REPLACE FUNCTION asociar_permiso(rol_key VARCHAR, rec_key VARCHAR, acc_key VARCHAR)
RETURNS VOID AS $$
DECLARE
  v_id_rol INT;
  v_id_rec INT;
  v_id_acc INT;
BEGIN
  SELECT id_rol INTO v_id_rol FROM "Roles" WHERE key = rol_key;
  SELECT id_recurso INTO v_id_rec FROM "Recursos" WHERE key = rec_key;
  SELECT id_accion INTO v_id_acc FROM "Acciones" WHERE key = acc_key;
  
  IF v_id_rol IS NOT NULL AND v_id_rec IS NOT NULL AND v_id_acc IS NOT NULL THEN
    INSERT INTO "Roles_Recursos_Acciones" (id_rol, id_recurso, id_accion)
    VALUES (v_id_rol, v_id_rec, v_id_acc)
    ON CONFLICT DO NOTHING;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Admin: TODOS los permisos de administración y gestión
SELECT asociar_permiso('administrador', 'admin', 'panel');
SELECT asociar_permiso('administrador', 'reportes', 'ver');
SELECT asociar_permiso('administrador', 'permisologia', 'gestionar_permisos');
SELECT asociar_permiso('administrador', 'sedes', 'gestionar');
SELECT asociar_permiso('administrador', 'servicios', 'gestionar');
SELECT asociar_permiso('administrador', 'personal', 'ver');
SELECT asociar_permiso('administrador', 'personal', 'crear');
SELECT asociar_permiso('administrador', 'personal', 'editar');
SELECT asociar_permiso('administrador', 'personal', 'eliminar');
SELECT asociar_permiso('administrador', 'roles', 'ver');
SELECT asociar_permiso('administrador', 'roles', 'crear');
SELECT asociar_permiso('administrador', 'roles', 'editar');
SELECT asociar_permiso('administrador', 'roles', 'eliminar');
SELECT asociar_permiso('administrador', 'especialidades', 'ver');
SELECT asociar_permiso('administrador', 'especialidades', 'crear');
SELECT asociar_permiso('administrador', 'especialidades', 'editar');
SELECT asociar_permiso('administrador', 'especialidades', 'eliminar');

-- Recepcionista: admisión:* y personal:ver
SELECT asociar_permiso('recepcionista', 'admision', '*');
SELECT asociar_permiso('recepcionista', 'personal', 'ver');

-- Médico: atencion_medica:* y acciones de consulta
SELECT asociar_permiso('medico', 'atencion_medica', '*');
SELECT asociar_permiso('medico', 'atencion_medica', 'llamar_siguiente');
SELECT asociar_permiso('medico', 'atencion_medica', 'liberar_consultorio');

-- Coordinador / Analista: aps:ver, aseguradoras:ver
SELECT asociar_permiso('coordinador', 'aps', 'ver');
SELECT asociar_permiso('coordinador', 'aseguradoras', 'ver');
SELECT asociar_permiso('analista', 'aps', 'ver');
SELECT asociar_permiso('analista', 'aseguradoras', 'ver');

-- Laboratorio: laboratorio:* y comodines de marcar ausente/reincorporar
SELECT asociar_permiso('laboratorio', 'laboratorio', '*');
SELECT asociar_permiso('laboratorio', '*', 'marcar_ausente');
SELECT asociar_permiso('laboratorio', '*', 'reincorporar');

-- Imagenes: imagenes:* y comodines de marcar ausente/reincorporar
SELECT asociar_permiso('imagenes', 'imagenes', '*');
SELECT asociar_permiso('imagenes', '*', 'marcar_ausente');
SELECT asociar_permiso('imagenes', '*', 'reincorporar');

-- Enfermero: admision:* y comodines de marcar ausente/reincorporar
SELECT asociar_permiso('enfermero', 'admision', '*');
SELECT asociar_permiso('enfermero', '*', 'marcar_ausente');
SELECT asociar_permiso('enfermero', '*', 'reincorporar');

-- Eliminar la función auxiliar
DROP FUNCTION asociar_permiso(VARCHAR, VARCHAR, VARCHAR);

-- USUARIOS
INSERT INTO "Usuarios" ("id_usuario", "cedula", "password_hash", "id_rol", "nombre", "apellido", "telefono", "id_consultorio", "id_servicio", "id_especialidad", "id_sede", "status") VALUES
  (2, '31693727', '$2b$10$/soHoDldxC32p0P0VXdKCuXKNaarqsseZhkrrSUMOdguApLaXdjii', 1, 'EDWARD', 'CEGARRA', '04141812042', NULL, NULL, NULL, 1, true),
  (10, '13893263', '$2b$10$WPrQGndyA4dV/qUQ4nlxz.Yj16m67aDXS8t9EQpFODVYdX7M4.r/2', 2, 'JESICA', 'PEREZ', '04242858057', NULL, NULL, NULL, 1, true),
  (11, '14737896', '$2b$10$1BnHhdVoPOkiIuNPslzGauDF6hGdRx9cFvBRcvZ/vR/qXP7WQKU26', 3, 'JEISON', 'MONTILLA', '0412587789', 1, NULL, 4, 1, true),
  (14, '14739777', '$2b$10$ORhgmthf.LPR..Kp5mc3cOzoVhGxLf/cQtwRzJKyocwQMP6n8tJIe', 1, 'MAICOL', 'ABREU', '0424587789', NULL, NULL, NULL, 2, true),
  (15, '13456789', '$2b$10$7bNox4TfFZXOKoW13ZnKBOz/cmVEQWiI7a0xWQiEg4PsrsDqJ83l2', 1, 'JUANA', 'HERNANDEZ', '04225741236', NULL, NULL, NULL, 1, true),
  (17, '10258789', '$2b$10$gMF9XAdlZcCYCZvbqhcKw.gG8a/YoLXFV/G1G9ZU3QeOY8eElXpn6', 3, 'JOSE', 'GUZMAN', '04141567896', 1, NULL, 5, 1, true),
  (18, '20123456', '$2b$10$sCi9d5y6Rr6qVkiFbqHVEuIy4W8brXsh5YcVJ1whu8NbP7UJJB/ya', 3, 'ADRIAN', 'HERNANDEZ', '04145878965', 4, 1, 5, 1, true),
  (43, '25789456', '$2b$10$/soHoDldxC32p0P0VXdKCuXKNaarqsseZhkrrSUMOdguApLaXdjii', 5, 'CARLOS', 'MENDOZA', '04141234567', NULL, NULL, NULL, 1, true),
  (44, '30125478', '$2b$10$/soHoDldxC32p0P0VXdKCuXKNaarqsseZhkrrSUMOdguApLaXdjii', 6, 'MARIA', 'GONZALEZ', '04145678901', NULL, NULL, NULL, 1, true),
  (49, '55555555', '$2b$10$/soHoDldxC32p0P0VXdKCuXKNaarqsseZhkrrSUMOdguApLaXdjii', 8, 'ENFERMERO', 'PRUEBA', '04140000000', NULL, NULL, NULL, 1, true);

-- PACIENTES
INSERT INTO "Pacientes" ("id_paciente", "cedula", "nombre", "apellido", "telefono", "id_sede") VALUES
  (1, '10236547', 'MARCO', 'POLO', '0422589789', 1),
  (3, '13893263', 'JEISON', 'MARTINEZ', '04242858057', 1),
  (5, '20312456', 'JUAN', 'PEREZ', '0414256366', 1),
  (6, '8521489', 'JEISON', 'MARTINEZ', '04225693125', 1),
  (11, '31789456', 'MONICA', 'CASTILLO', '04243698521', 1),
  (12, '12456789', 'JOSEFINA', 'PEREZ', '04141597890', 1),
  (13, '12369789', 'JUAN', 'OBISPO', '04242851563', 1),
  (14, '10236589', 'MAICOL', 'JUAREZ', '04225877896', 1),
  (15, '17258963', 'JENIFER', 'LOPEZ', '04223658956', 1),
  (16, '14258236', 'PEDRO', 'MEO', '04124567896', 1),
  (17, '8789456', 'MARCOS', 'RIOS', '04241234569', 1),
  (18, '31693787', 'SOFIA', 'MORA', '041415623698', 1),
  (19, '14598639', 'MARLON', 'PEREZ', '04141812045', 1);

-- ======================================================
-- RESETEAR SECUENCIAS
-- ======================================================
SELECT pg_catalog.setval('public."Consultorios_id_consultorio_seq"', 20, true);
SELECT pg_catalog.setval('public."Especialidades_id_especialidad_seq"', 8, true);
SELECT pg_catalog.setval('public."Estado_id_estado_seq"', 8, true);
SELECT pg_catalog.setval('public."Pacientes_id_paciente_seq"', 19, true);
SELECT pg_catalog.setval('public."Responsable_Pago_id_responsable_seq"', 4, true);
SELECT pg_catalog.setval('public."Servicio_id_servicio_seq"', 7, true);
SELECT pg_catalog.setval('public."Usuarios_id_usuario_seq"', 49, true);
SELECT pg_catalog.setval('public."Atencion_id_atencion_seq"', 27, true);
SELECT pg_catalog.setval('public."Historial_Atencion_id_historial_seq"', 55, true);
SELECT pg_catalog.setval('public.cliente_id_cliente_seq', 2, true);
SELECT pg_catalog.setval('public.tipo_cliente_id_tipo_cliente_seq', 1, false);
