CREATE TABLE IF NOT EXISTS "Recuperacion_Clave" (
  "id_recuperacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INTEGER NOT NULL REFERENCES "Usuarios"("id_usuario"),
  "codigo" VARCHAR(6) NOT NULL,
  "expiracion" TIMESTAMP NOT NULL,
  "usado" BOOLEAN DEFAULT false,
  "fecha_creacion" TIMESTAMP DEFAULT (now())
);
